@TodoList_HostAddress = http://localhost:5076

DELETE {{TodoList_HostAddress}}/api/tag/6

### Update tag id = 6 (success case)
PUT {{TodoList_HostAddress}}/api/tag/6
Content-Type: application/json

{
  "tagName": "Updated Tag"
}

### Update tag không tồn tại (expect 404 NotFound)
PUT {{TodoList_HostAddress}}/api/tag/99999
Content-Type: application/json

{
  "tagName": "Should Not Exist"
}
